apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
  labels:
    cloud: 'Azure'
    region: {{ .Values.region }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
spec:
  baseDomain: {{ .Values.baseDomain }}
  clusterName: {{ .Values.clusterName }}
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  installed: false
  platform:
    azure:
      baseDomainResourceGroupName: {{ .Values.resourcegroup }}
      credentialsSecretRef:
        name: {{ .Values.common.azureCredentials }}
      region: {{ .Values.region }}
      cloudName: AzurePublicCloud
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.clusterName }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.common.sshPrivateKey }}
    imageSetRef:
      name: img{{ .Values.ocpVersion }}-multi-appsub
  pullSecretRef:
    name: {{ .Values.common.ocpPullSecretName }}
